### ISSUE TITLE
Read Me Instructions

### ISSUE THREAD

**Issue by 0xSeanG** [blauwers/wp-isc2-chapter-theme#1]
Per https://isc2-austin-chapter.org/resources/isc%C2%B2-chapter-theme-wordpress/ basic instructions for forking, updating for our chapter logos, and deploying would be in the Repo - any chance this just wasn't committed, or this is planned?

**Comment by blauwers** [comment]
We are still working on that documentation. Is there anything in specific you wish to know at this time? Our goal is to make it easy for all chapters to have a nice looking chapter site, so we'd be happy to share any information to accomplish this.

**Comment by blauwers** [comment]
I just pushed the initial version of the documentation to the repository. Please let us know if you have remaining questions about how to use the theme. # abcda63d76d55a0b58308e7d895d2a806758d439

**Comment by 0xSeanG** [comment]
Sorry for my delayed response. I appreciate you updating the readme, the updated version addressed the questions I had.
